url: "https://jingtianIS.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Jing Tian" # the name of your site, e.g. ACME Corp.
description: "AI Augmented System, Digital Platform, Corporate IT Strategy"
email: jtian9@gsu.edu
