menu:
# - {name: 'people', url: '/people'}
- {name: 'Home', url: ''}
# - {name: 'Reseach', url: '/research'}
- {name: 'Publications', url: '/publications'}
# - {name: 'courses', url: '/courses'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

people:

courses:

social:
- {icon: 'github', link: 'https://github.com/jingtianIS'}
