menu:
# - {name: 'people', url: '/people'}
- {name: 'Home', url: ''}
# - {name: 'Reseach', url: '/research'}
- {name: 'Publications', url: '/publications'}
# - {name: 'courses', url: '/courses'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

people:

courses:

social:
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/jing-tian-6a4b55191/'}
- {icon: 'github', link: 'https://github.com/jingtianIS'}

contacts:
- {name: 'Jing Tian', email: 'jtian9 at gsu.edu', image: "assets/img/contact.jpg"}
